declare global {
    namespace NodeJs{
        interface ProcessEnv{
            NEXT_PUBLIC_SUPABESE_URL: string;
            NEXT_PUBLIC_SUPABESE_ANON_KEY: string;
            REPLICATE_API_TOLKEN: string;
               
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_FOLDER: string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_FOLDER_RESTORED: string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_FOLDER_PROCESSING: string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_PUBLIC_URL:string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_URL: string;
            
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_FOLDER_RECRIENTION:string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_FOLDER_RESTORED_RECRIENTION:string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_FOLDER_PROCESSING_RECRIENTION:string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_PUBLIC_URL_RECRIENTION:string;
            NEXT_PUBLIC_SUPABESE_APP_BUCKET_IMAGE_URL_RECRIENTION:string;
            REPLICATE_API_TOLKEN_RECRIENTION:string;
        }
    }
}

export  {}